name: Refactor (Maintainers)
description: Used to track refactoring opportunities
title: "Refactor: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Check [existing ESE issues](https://github.com/xero00000/expert-streaming-engine/issues?q=is%3Aissue+refactor)
        and [open pull requests](https://github.com/xero00000/expert-streaming-engine/pulls?q=is%3Apr+is%3Aopen+refactor)
        before opening a duplicate refactor ticket.

  - type: textarea
    id: background-description
    attributes:
      label: Background Description
      description: Please provide a detailed written description of the pain points you are trying to solve.
      placeholder: Detailed description behind your motivation to request refactor
    validations:
      required: true

  - type: textarea
    id: possible-approaches
    attributes:
      label: Possible Refactor Approaches
      description: If you have some idea of possible approaches to solve this problem. You may want to make it a todo list.
      placeholder: Your idea of possible refactoring opportunity/approaches
    validations:
      required: false
